-- ================================================
-- Script de Configuração do Banco de Dados
-- API de Créditos Constituídos
-- ================================================

-- Criar banco de dados (executar como superuser)
-- DROP DATABASE IF EXISTS creditodb;
CREATE DATABASE creditodb
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

-- Conectar ao banco creditodb
\c creditodb

-- ================================================
-- Criar tabela de créditos
-- ================================================

CREATE TABLE IF NOT EXISTS credito
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_credito    VARCHAR(50)    NOT NULL,
    numero_nfse       VARCHAR(50)    NOT NULL,
    data_constituicao DATE           NOT NULL,
    valor_issqn       DECIMAL(15, 2) NOT NULL,
    tipo_credito      VARCHAR(50)    NOT NULL,
    simples_nacional  BOOLEAN        NOT NULL,
    aliquota          DECIMAL(5, 2)  NOT NULL,
    valor_faturado    DECIMAL(15, 2) NOT NULL,
    valor_deducao     DECIMAL(15, 2) NOT NULL,
    base_calculo      DECIMAL(15, 2) NOT NULL,
    CONSTRAINT pk_credito PRIMARY KEY (id)
);

-- ================================================
-- Criar índices para otimização de consultas
-- ================================================

CREATE INDEX IF NOT EXISTS idx_numero_credito 
    ON credito (numero_credito);

CREATE INDEX IF NOT EXISTS idx_numero_nfse 
    ON credito (numero_nfse);

-- ================================================
-- Comentários nas colunas (documentação)
-- ================================================

COMMENT ON TABLE credito IS 'Tabela de créditos constituídos';

COMMENT ON COLUMN credito.id IS 'Identificador único do crédito';
COMMENT ON COLUMN credito.numero_credito IS 'Número identificador do crédito constituído';
COMMENT ON COLUMN credito.numero_nfse IS 'Número da Nota Fiscal de Serviços Eletrônica';
COMMENT ON COLUMN credito.data_constituicao IS 'Data de constituição do crédito';
COMMENT ON COLUMN credito.valor_issqn IS 'Valor do Imposto Sobre Serviços de Qualquer Natureza';
COMMENT ON COLUMN credito.tipo_credito IS 'Tipo do crédito (ISSQN, Outros, etc)';
COMMENT ON COLUMN credito.simples_nacional IS 'Indica se é optante pelo Simples Nacional';
COMMENT ON COLUMN credito.aliquota IS 'Alíquota aplicada ao crédito';
COMMENT ON COLUMN credito.valor_faturado IS 'Valor total faturado';
COMMENT ON COLUMN credito.valor_deducao IS 'Valor de dedução aplicado';
COMMENT ON COLUMN credito.base_calculo IS 'Base de cálculo do crédito';

-- ================================================
-- Dados de exemplo (opcional - para testes)
-- ================================================

-- Inserir créditos de exemplo
INSERT INTO credito (
    numero_credito, 
    numero_nfse, 
    data_constituicao, 
    valor_issqn, 
    tipo_credito, 
    simples_nacional, 
    aliquota, 
    valor_faturado, 
    valor_deducao, 
    base_calculo
) VALUES 
(
    '123456',
    '7891011',
    '2024-02-25',
    1500.75,
    'ISSQN',
    true,
    5.0,
    30000.00,
    5000.00,
    25000.00
),
(
    '789012',
    '7891011',
    '2024-02-26',
    1200.50,
    'ISSQN',
    false,
    4.5,
    25000.00,
    4000.00,
    21000.00
),
(
    '654321',
    '1122334',
    '2024-01-15',
    800.50,
    'Outros',
    true,
    3.5,
    20000.00,
    3000.00,
    17000.00
)
ON CONFLICT DO NOTHING;

-- ================================================
-- Verificar dados inseridos
-- ================================================

SELECT 
    id,
    numero_credito,
    numero_nfse,
    data_constituicao,
    valor_issqn,
    tipo_credito,
    CASE WHEN simples_nacional THEN 'Sim' ELSE 'Não' END as simples_nacional,
    aliquota,
    valor_faturado,
    valor_deducao,
    base_calculo
FROM credito
ORDER BY id;

-- ================================================
-- Consultas úteis para análise
-- ================================================

-- Total de créditos por tipo
SELECT 
    tipo_credito,
    COUNT(*) as quantidade,
    SUM(valor_issqn) as valor_total_issqn
FROM credito
GROUP BY tipo_credito
ORDER BY valor_total_issqn DESC;

-- Créditos por NFS-e
SELECT 
    numero_nfse,
    COUNT(*) as quantidade_creditos,
    SUM(valor_issqn) as valor_total
FROM credito
GROUP BY numero_nfse
ORDER BY quantidade_creditos DESC;

-- Créditos optantes pelo Simples Nacional
SELECT 
    COUNT(*) as total_simples_nacional,
    SUM(valor_issqn) as valor_total
FROM credito
WHERE simples_nacional = true;

-- ================================================
-- Funções úteis
-- ================================================

-- Função para buscar créditos por período
CREATE OR REPLACE FUNCTION buscar_creditos_por_periodo(
    data_inicio DATE,
    data_fim DATE
)
RETURNS TABLE (
    numero_credito VARCHAR(50),
    numero_nfse VARCHAR(50),
    data_constituicao DATE,
    valor_issqn DECIMAL(15,2),
    tipo_credito VARCHAR(50)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        c.numero_credito,
        c.numero_nfse,
        c.data_constituicao,
        c.valor_issqn,
        c.tipo_credito
    FROM credito c
    WHERE c.data_constituicao BETWEEN data_inicio AND data_fim
    ORDER BY c.data_constituicao DESC;
END;
$$ LANGUAGE plpgsql;

-- Exemplo de uso:
-- SELECT * FROM buscar_creditos_por_periodo('2024-01-01', '2024-12-31');

-- ================================================
-- View para relatório consolidado
-- ================================================

CREATE OR REPLACE VIEW vw_creditos_consolidado AS
SELECT 
    c.id,
    c.numero_credito,
    c.numero_nfse,
    c.data_constituicao,
    c.valor_issqn,
    c.tipo_credito,
    CASE WHEN c.simples_nacional THEN 'Sim' ELSE 'Não' END as simples_nacional,
    c.aliquota,
    c.valor_faturado,
    c.valor_deducao,
    c.base_calculo,
    -- Campos calculados
    (c.valor_faturado - c.valor_deducao) as valor_liquido,
    ROUND((c.valor_issqn / c.base_calculo * 100), 2) as percentual_issqn
FROM credito c;

-- Exemplo de uso:
-- SELECT * FROM vw_creditos_consolidado WHERE tipo_credito = 'ISSQN';

-- ================================================
-- Permissões (ajustar conforme necessário)
-- ================================================

-- Conceder permissões ao usuário da aplicação
GRANT SELECT, INSERT, UPDATE, DELETE ON credito TO postgres;
GRANT USAGE, SELECT ON SEQUENCE credito_id_seq TO postgres;
GRANT SELECT ON vw_creditos_consolidado TO postgres;

-- ================================================
-- Backup e Manutenção
-- ================================================

-- Comando para backup (executar no terminal)
-- pg_dump -U postgres -d creditodb -F c -b -v -f creditodb_backup.backup

-- Comando para restore (executar no terminal)
-- pg_restore -U postgres -d creditodb -v creditodb_backup.backup

-- ================================================
-- Limpeza (usar com cuidado!)
-- ================================================

-- Remover todos os dados (manter estrutura)
-- TRUNCATE TABLE credito RESTART IDENTITY CASCADE;

-- Remover tabela completamente
-- DROP TABLE IF EXISTS credito CASCADE;

-- Remover view
-- DROP VIEW IF EXISTS vw_creditos_consolidado;

-- Remover função
-- DROP FUNCTION IF EXISTS buscar_creditos_por_periodo(DATE, DATE);

-- ================================================
-- Estatísticas e Performance
-- ================================================

-- Analisar tabela para otimização de queries
ANALYZE credito;

-- Verificar tamanho da tabela
SELECT 
    pg_size_pretty(pg_total_relation_size('credito')) as tamanho_total,
    pg_size_pretty(pg_relation_size('credito')) as tamanho_tabela,
    pg_size_pretty(pg_indexes_size('credito')) as tamanho_indices;

-- Verificar uso dos índices
SELECT 
    schemaname,
    tablename,
    indexname,
    idx_scan as numero_scans,
    idx_tup_read as tuplas_lidas,
    idx_tup_fetch as tuplas_buscadas
FROM pg_stat_user_indexes
WHERE tablename = 'credito'
ORDER BY idx_scan DESC;

-- ================================================
-- Fim do script
-- ================================================

\echo 'Setup do banco de dados concluído com sucesso!'
\echo 'Tabela: credito'
\echo 'Índices: idx_numero_credito, idx_numero_nfse'
\echo 'View: vw_creditos_consolidado'
\echo 'Função: buscar_creditos_por_periodo'
